export const IMAGES = {
  southAfricaFlag: require('./icons/sa-flag.png'),
  bitCoin: require('./icons/bitcoin.png'),
  blankRoundImage: require('./icons/blank-image.png'),
  logoImage: require('./icons/StandardBankLogo.png'),
  cartImage: require('./icons/cart.png'),
  logoutImage: require('./icons/logout.png'),
  walletImage: require('./icons/wallet.png'),
  sendImage: require('./icons/send.png'),
  buySellImage: require('./icons/buySell.png'),
  portfolioImage: require('./icons/portfolio.png'),
  upArrowImage: require('./icons/upArrow.png'),
  downArrowImage: require('./icons/downArrow.png'),
  withdrawImage: require('./icons/withdraw.png'),
  depositImage: require('./icons/deposit.png'),
  menuImage: require('./icons/menu.png'),
  lineImage: require('./icons/line.png'),
  forwardArrowImage: require('./icons/forwardarrow.png'),
};
