apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-service-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam-service
  template:
    metadata:
      labels:
        app: iam-service
    spec:
      containers:
      - name: iam-service
        image: 571981719758.dkr.ecr.ca-central-1.amazonaws.com/iam-production:305
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: iam-secret-prod
---
apiVersion: v1
kind: Service
metadata: 
  name: iam-service
  namespace: default
  labels:
    app: iam-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      # targetPort: 3001
  selector:
    app: iam-service
