// Manage routes constants
export const ROUTES = {
  DEPOSIT: 'DEPOSIT',
  FOOTER: 'FOOTER',
  WITHDRAW: 'WITHDRAW',
  WALLET: 'WALLET',
  TOKEN_BUY_SELL: 'TOKEN_BUY_SELL',
  DEPOSIT_DETAILS: 'DEPOSIT_DETAILS',
  SIGNIN: 'SIGNIN',
  SIGNUP: 'SIGNUP',
  AUTH_SCREEN: 'AUTH_SCREEN',
  TRANSACTION_DETAIL: 'TRANSACTION_DETAIL',
};
