import {StyleSheet} from 'react-native';
import {COLORS} from '../../../styles/Colors';

export const styles = StyleSheet.create({
  headerContainer: {
    width: '100%',
    height: 200,
    backgroundColor: '#3770ff',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    flex: 1,
    borderRadius: 30,
    display: 'flex',
    flexDirection: 'row',
  },
  mainContainer: {
    width: '100%',
    height: '10%',
    backgroundColor: COLORS.BLUE,
    justifyContent: 'center',
    position: 'relative', //Here is the trick
    bottom: 0, //Here is the trick,
    flex: 1,
    borderRadius: 30,
    display: 'flex',
    flexDirection: 'row',
    marginTop: 150,
  },
  footerContainer: {
    width: '100%',
    height: 70,
    backgroundColor: '#3770ff',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'absolute', //Here is the trick
    bottom: 0, //Here is the trick,
    flex: 1,
    borderRadius: 30,
    display: 'flex',
    flexDirection: 'row',
  },
  mainTitle: {
    marginLeft: 30,
    marginTop: 30,
    alignSelf: 'flex-start',
    color: COLORS.WHITE,
    fontWeight: 'bold',
    fontSize: 20,
  },
  imageLayout: {
    alignItems: 'flex-end',
    marginRight: 30,
    marginTop: 30,
  },
  titleImage: {
    justifyContent: 'space-between',
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
  },
  sectionTabImageWrapper: {
    borderRadius: 50,
    width: 50,
    height: 50,
    position: 'relative',
    marginLeft: 40,
    marginRight: 40,
    backgroundColor: COLORS.SECONDARY_BLUE,
  },
  borderBlock: {
    width: '90%',
    height: 90,
    backgroundColor: '#3770ff',
    alignItems: 'center',
    position: 'absolute',
    flex: 1,
    borderRadius: 30,
    display: 'flex',
    flexDirection: 'column',
    marginTop: 100,
    justifyContent: 'space-between',
    padding: 10,
  },
  borderTitle: {
    color: COLORS.WHITE,
    fontSize: 16,
  },
  amountText: {
    color: COLORS.WHITE,
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  transactionData: {
    position: 'absolute',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    marginTop: 200,
    justifyContent: 'center',
    padding: 10,
  },
  transactionRow: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 5,
  },
  titleColor: {
    color: COLORS.WHITE,
    fontSize: 16,
    textAlign: 'left',
  },
  valueColor: {
    color: COLORS.WHITE,
    fontSize: 16,
    textAlign: 'right',
  },
  lineWrapper: {
    marginBottom: 35,
    width: 50,
    height: 50,
    position: 'relative',
    marginLeft: 12,
    marginRight: 12,
  },
  sectionHeadImageWrapper: {
    borderRadius: 50,
    backgroundColor: COLORS.SECONDARY_BLUE,
  },
});
