export default {
  login: "wesbos",
  id: 176013,
  node_id: "MDQ6VXNlcjE3NjAxMw==",
  avatar_url: "https://avatars.githubusercontent.com/u/176013?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/wesbos",
  html_url: "https://github.com/wesbos",
  followers_url: "https://api.github.com/users/wesbos/followers",
  following_url: "https://api.github.com/users/wesbos/following{/other_user}",
  gists_url: "https://api.github.com/users/wesbos/gists{/gist_id}",
  starred_url: "https://api.github.com/users/wesbos/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/wesbos/subscriptions",
  organizations_url: "https://api.github.com/users/wesbos/orgs",
  repos_url: "https://api.github.com/users/wesbos/repos",
  events_url: "https://api.github.com/users/wesbos/events{/privacy}",
  received_events_url: "https://api.github.com/users/wesbos/received_events",
  type: "User",
  site_admin: false,
  name: "Wes Bos",
  company: "me",
  blog: "www.wesbos.com",
  location: "Hamilton, Ontario",
  email: null,
  hireable: true,
  bio: "I create courses that make learning things like JavaScript easy and fun 🔥",
  twitter_username: null,
  public_repos: 305,
  public_gists: 63,
  followers: 28592,
  following: 31,
  created_at: "2010-01-04T10:11:44Z",
  updated_at: "2022-05-06T15:26:39Z",
};

// {
//   login: "MonaliGanganeNeosoft",
//   id: 90671888,
//   node_id: "MDQ6VXNlcjkwNjcxODg4",
//   avatar_url: "https://avatars.githubusercontent.com/u/90671888?v=4",
//   gravatar_id: "",
//   url: "https://api.github.com/users/MonaliGanganeNeosoft",
//   html_url: "https://github.com/MonaliGanganeNeosoft",
//   followers_url: "https://api.github.com/users/MonaliGanganeNeosoft/followers",
//   following_url: "https://api.github.com/users/MonaliGanganeNeosoft/following{/other_user}",
//   gists_url: "https://api.github.com/users/MonaliGanganeNeosoft/gists{/gist_id}",
//   starred_url: "https://api.github.com/users/MonaliGanganeNeosoft/starred{/owner}{/repo}",
//   subscriptions_url: "https://api.github.com/users/MonaliGanganeNeosoft/subscriptions",
//   organizations_url: "https://api.github.com/users/MonaliGanganeNeosoft/orgs",
//   repos_url: "https://api.github.com/users/MonaliGanganeNeosoft/repos",
//   events_url: "https://api.github.com/users/MonaliGanganeNeosoft/events{/privacy}",
//   received_events_url: "https://api.github.com/users/MonaliGanganeNeosoft/received_events",
//   type: "User",
//   site_admin: false,
//   name: null,
//   company: null,
//   blog: "",
//   location: null,
//   email: null,
//   hireable: null,
//   bio: null,
//   twitter_username: null,
//   public_repos: 39,
//   public_gists: 0,
//   followers: 0,
//   following: 0,
//   created_at: "2021-09-14T04:58:54Z",
//   updated_at: "2022-05-04T08:01:23Z"
//   }
